pages:
  image: debian:stable-slim
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install -y make lowdown
  script:
    - make clean
    - make
  artifacts:
    paths:
      - public
  only:
    - master
